// USER
export const FETCHING_AUTH = 'FETCHING_AUTH'
export const FETCHING_AUTH_COMPLETE = 'FETCHING_AUTH_COMPLETE'
export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'
export const RECEIVE_CALL_TAGS = 'RECEIVE_CALL_TAGS'
export const RECEIVE_ONBEHALF = 'RECEIVE_ONBEHALF'
export const USER_INFO_UPDATED = 'USER_INFO_UPDATED'
export const SET_COACH_CURRENT_STAFF = 'SET_COACH_CURRENT_STAFF'
export const TOKEN_CHECK_COMPLETE = 'TOKEN_CHECK_COMPLETE'
export const USER_INFO_SUBMITTING = 'USER_INFO_SUBMITTING'
export const UPDATE_TERMS_AGREEMENT = 'UPDATE_TERMS_AGREEMENT'

// CONTACTS
export const LOAD_MORE_CONTACTS = 'LOAD_MORE_CONTACTS'
export const CONTACTS_LOADED = 'CONTACTS_LOADED'
export const MORE_CONTACTS_LOADED = 'MORE_CONTACTS_LOADED'
export const ADD_CONTACT = 'ADD_CONTACT'
export const UPDATE_CONTACT_QUERY = 'UPDATE_CONTACT_QUERY'
export const RECEIVE_WID_FIELDS = 'RECEIVE_WID_FIELDS'
export const TOGGLE_LIST_CONTACT_FROZEN = 'TOGGLE_LIST_CONTACT_FROZEN'
export const CONTACT_UPDATED = 'CONTACT_UPDATED'
export const UPDATING_CONTACT = 'UPDATING_CONTACT'

// CURRENT CONTACT
export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT'
export const CLEAR_CURRENT_CONTACT = 'CLEAR_CURRENT_CONTACT'
export const LOAD_NOTES = 'LOAD_NOTES'
export const LOAD_NOTES_FAIL = 'LOAD_NOTES_FAIL'
export const LOADING_CURRENT_CONTACT = 'LOADING_CURRENT_CONTACT'
export const LOADING_CURRENT_CONTACT_COMPLETE = 'LOADING_CURRENT_CONTACT_COMPLETE'

// CURRENT STAFF
export const SET_CURRENT_STAFF = 'SET_CURRENT_STAFF'

// VOICE ACTIVITIES
export const VOICE_ACTIVITIES_LOADED = 'VOICE_ACTIVITIES_LOADED'
export const MORE_VOICE_ACTIVITIES_LOADED = 'MORE_VOICE_ACTIVITIES_LOADED'
export const TAG_CALL = 'TAG_CALL'
export const LOADING_MORE_VOICE_ACTIVITIES = 'LOADING_MORE_VOICE_ACTIVITIES'
export const LOAD_VOICE_ACTIVITIES_ERROR = 'LOAD_VOICE_ACTIVITIES_ERROR'

// ACTIVITIES
export const ACTIVITIES_LOADED = 'ACTIVITIES_LOADED'
export const MORE_ACTIVITIES_LOADED = 'MORE_ACTIVITIES_LOADED'
export const APPEND_TO_ACTIVITIES = 'APPEND_TO_ACTIVITIES'
export const SET_NEW_ACTIVITY = 'SET_NEW_ACTIVITY'
export const LOADING_ACTIVITIES = 'LOADING_ACTIVITIES'
export const LOADING_ACTIVITIES_COMPLETE = 'LOADING_ACTIVITIES_COMPLETE'
export const LOADING_MORE_ACTIVITIES = 'LOADING_MORE_ACTIVITIES'

// CONVERSATION
export const SET_CONVERSATION = 'SET_CONVERSATION'
export const SET_MORE_CONVERSATION = 'SET_MORE_CONVERSATION'
export const APPEND_TO_CONVERSATION = 'APPEND_TO_CONVERSATION'
export const LOADING_CONVERSATION = 'LOADING_CONVERSATION'
export const LOADING_MORE_CONVERSATION = 'LOADING_MORE_CONVERSATION'
export const UPDATE_CONVERSATION_ITEM = 'UPDATE_CONVERSATION_ITEM'

// MASSMESSAGES
export const RECEIVE_MESSAGE_PREVIEW = 'RECEIVE_MESSAGE_PREVIEW'
export const SET_MM_FORM_FROM_PREVIEW = 'SET_MM_FORM_FROM_PREVIEW'
export const RESET_MM_FORM = 'RESET_MM_FORM'
export const REMOVE_RECIPIENT_MMFORM = 'REMOVE_RECIPIENT_MMFORM'
export const CLEAR_MESSAGE_PREVIEW = 'CLEAR_MESSAGE_PREVIEW'
export const FETCH_RECEIVE_MESSAGE_PREVIEW = 'FETCH_RECEIVE_MESSAGE_PREVIEW'
export const ADD_RECIPIENT = 'ADD_RECIPIENT'
export const ADD_RECIPIENT_LIST = 'ADD_RECIPIENT_LIST'
export const REMOVE_RECIPIENT = 'REMOVE_RECIPIENT'
export const REMOVE_RECIPIENT_LIST = 'REMOVE_RECIPIENT_LIST'
export const UPDATE_MM_FORM = 'UPDATE_MM_FORM'
export const CLEAR_RECIPIENTS = 'CLEAR_RECIPIENTS'
export const SUBMITTING_MASS_MESSAGE = 'SUBMITTING_MASS_MESSAGE'
export const STOP_SUBMITTING_MASS_MESSAGE = 'STOP_SUBMITTING_MASS_MESSAGE'
export const UPDATE_RECIPIENT = 'UPDATE_RECIPIENT'
export const IS_SELECTING_LIST = 'IS_SELECTING_LIST'
export const REMOVE_MEDIA = 'REMOVE_MEDIA'

// NOTES
export const RECEIVED_NOTES = 'RECEIVED_NOTES'
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const CLEAR_NOTES = 'CLEAR_NOTES'

// LISTS
export const RECEIVE_LISTS = 'RECEIVE_LISTS'
export const RECEIVE_LIST = 'RECEIVE_LIST'
export const FETCH_LISTS = 'FETCH_LISTS'

//IMAGES
export const RECEIVED_IMAGE = 'RECEIVED_IMAGE'